# Generated by Django 3.2.7 on 2021-09-06 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_form_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='boxes',
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.UUIDField(default='')),
                ('title', models.CharField(default='UntitledBox', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('hasCon', models.BooleanField(default=False)),
                ('problems', models.JSONField(default=list)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box', to='api.form')),
            ],
        ),
    ]
