# Generated by Django 3.2.7 on 2021-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_box_from_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='box',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Box',
        ),
    ]
