# Generated by Django 3.2.7 on 2021-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210907_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='box',
            field=models.JSONField(default=list),
        ),
    ]
