# Generated by Django 3.2.7 on 2021-09-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
