# Generated by Django 3.2.7 on 2021-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_form_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forms',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar'),
        ),
    ]
