# Generated by Django 3.2.7 on 2021-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='start_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
